name: lizhutchinsonjewellery
favicon: null
layout_spectrum: 0.14733
typography_spectrum: 0.8122873506508768
title: Liz Hutchinson Jewellery
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9e9667'
    - '#f1f3f2'
    - '#837548'
    - '#b97c00'
    - '#efd884'
  brandStrength: 0.0625
  lightness: 0.9299168649595231
  saturation: 0.5401093650143594
  rhythmicContrast: 0.26060450193472207
purpose: []
